services:
  # Development service
  app-dev:
    build: .
    volumes:
      - .:/app
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - RATELIMIT_STORAGE_URI=memcached://memcached:11211
    command: python run.py
    restart: unless-stopped
    depends_on:
      - memcached

  # Memcached service for rate limiting
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: unless-stopped

  # Separate service for database operations and management commands
  manage:
    build: .
    volumes:
      - .:/app
    entrypoint: ["./manage.py"]
    profiles:
      - tools
    depends_on:
      - app-dev

# This application is designed to be used exclusively via Docker Compose