"""add_waf_advanced_settings_to_site_model

Revision ID: 6b3a9088d441
Revises: a12e3695b0db
Create Date: 2025-04-23 21:59:06.886339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3a9088d441'
down_revision = 'a12e3695b0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waf_rule_level', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('waf_custom_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('waf_max_request_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waf_request_timeout', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waf_block_tor_exit_nodes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('waf_rate_limiting_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('waf_rate_limiting_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waf_rate_limiting_burst', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('waf_rate_limiting_burst')
        batch_op.drop_column('waf_rate_limiting_requests')
        batch_op.drop_column('waf_rate_limiting_enabled')
        batch_op.drop_column('waf_block_tor_exit_nodes')
        batch_op.drop_column('waf_request_timeout')
        batch_op.drop_column('waf_max_request_size')
        batch_op.drop_column('waf_custom_rules')
        batch_op.drop_column('waf_rule_level')

    # ### end Alembic commands ###
