"""add_node_id_to_ssl_certificates

Revision ID: 7709fc32742e
Revises: bc43543e2dcc
Create Date: 2025-04-23 19:46:29.736180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7709fc32742e'
down_revision = 'bc43543e2dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssl_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('node_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('subject', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('fingerprint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('valid_from', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('days_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_wildcard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_self_signed', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_ssl_certificates_node_id', 'nodes', ['node_id'], ['id'])
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssl_certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('fk_ssl_certificates_node_id', type_='foreignkey')
        batch_op.drop_column('is_self_signed')
        batch_op.drop_column('is_wildcard')
        batch_op.drop_column('days_remaining')
        batch_op.drop_column('valid_until')
        batch_op.drop_column('valid_from')
        batch_op.drop_column('fingerprint')
        batch_op.drop_column('subject')
        batch_op.drop_column('node_id')

    # ### end Alembic commands ###
