"""add_cache_configuration_fields_to_site_model

Revision ID: 82935383684c
Revises: dc651068f3ab
Create Date: 2025-04-23 17:05:35.196483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82935383684c'
down_revision = 'dc651068f3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_cache', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cache_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cache_static_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('custom_cache_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cache_browser_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('cache_browser_time')
        batch_op.drop_column('custom_cache_rules')
        batch_op.drop_column('cache_static_time')
        batch_op.drop_column('cache_time')
        batch_op.drop_column('enable_cache')

    # ### end Alembic commands ###
