"""add_owasp_crs_fields_to_site_model

Revision ID: 924af986c638
Revises: 6b3a9088d441
Create Date: 2025-04-24 00:29:29.080986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924af986c638'
down_revision = '6b3a9088d441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waf_use_owasp_crs', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('waf_owasp_crs_paranoia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('waf_enabled_crs_rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('waf_disabled_crs_rules', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('waf_disabled_crs_rules')
        batch_op.drop_column('waf_enabled_crs_rules')
        batch_op.drop_column('waf_owasp_crs_paranoia')
        batch_op.drop_column('waf_use_owasp_crs')

    # ### end Alembic commands ###
