"""Add detected_nginx_path to Node model

Revision ID: bc43543e2dcc
Revises: 19d3bff28610
Create Date: 2025-04-23 17:49:50.912753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc43543e2dcc'
down_revision = '19d3bff28610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detected_nginx_path', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('detected_nginx_path')

    # ### end Alembic commands ###
